---
title: "WebScrapping"
author: "JP"
date: "6/5/2020"
output:
  html_document: default
  pdf_document: default
---
# Webscrapping of Billboard Top 100 Songs
code courtesy of Keith McNulty 8/2019
https://towardsdatascience.com/tidy-web-scraping-in-r-tutorial-and-resources-ac9f72b4fe47

```{r Setup-Load-Libraries}
if (!("rvest" %in% installed.packages())) {install.packages("rvest")}
if (!("dplyr" %in% installed.packages())) {install.packages("dplyr")}

library(rvest)
library(dplyr)
```
# Getting Started

```{r Read Billboard site data}
hot100page <- "https://www.billboard.com/charts/hot-100"
hot100 <- read_html(hot100page)
hot100
str(hot100)
```

The function has captured the entire content of the page in the form of a special list-type document with two nodes <head> and <body>. Almost always we are interested in the body of a web page. You can select a node using html_node() and then see its child nodes using html_children().

```{r}
body_nodes <- hot100 %>% 
  html_node("body") %>%
  html_children()

body_nodes

```

```{r}
rank <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__rank__number')]") %>% 
  rvest::html_text()
artist <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__information__artist')]") %>% 
  rvest::html_text()
title <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__information__song')]") %>% 
  rvest::html_text()
```

```{r}
chart_df <- data.frame(rank, artist, title)
# knitr::kable(
  chart_df  %>% head(10)
```

